name: Pull Request Test

on: [pull_request]

jobs:
  test:
    name: Test on Windows
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      
      - name: Download Premake
        uses: abel0b/setup-premake@v2.4
        with:
          version: "5.0.0-beta2"
    
      - name: Build
        shell: bash
        run: |
          CI/build.sh

      - name: Set Artifact Name with Date
        shell: bash
        run: |
          echo "LIGHTFX_ARTIFACT_NAME=lightmap-tools-win32-$(date +%Y%m%d)" >> $GITHUB_ENV
          echo "UVUNWRAP_ARTIFACT_NAME=uvunwrap-tools_win32_$(date +%Y%m%d)" >> $GITHUB_ENV

      - name: Upload LightFX Artifact
        uses: actions/upload-artifact@v4
        with: 
          name: ${{ env.LIGHTFX_ARTIFACT_NAME }}
          path: build/bin/LightFX

      - name: Upload uvunwrap Artifact
        uses: actions/upload-artifact@v4
        with: 
          name: ${{ env.UVUNWRAP_ARTIFACT_NAME }}
          path: build/bin/uvunwrap

  test_on_mac:
    name: Test on macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - name: Download Premake
        uses: abel0b/setup-premake@v2.4
        with:
          version: "5.0.0-beta2"
  
      - name: Build
        shell: bash
        run: |
          CI/build.sh

      - name: Set Artifact Name with Date
        run: |
           echo "LIGHTFX_ARTIFACT_NAME=lightmap-tools-darwin-$(date +%Y%m%d)" >> $GITHUB_ENV
           echo "UVUNWRAP_ARTIFACT_NAME=uvunwrap-tools_darwin_$(date +%Y%m%d)" >> $GITHUB_ENV


      - name: Upload LightFX Artifact
        uses: actions/upload-artifact@v4
        with: 
          name: ${{ env.LIGHTFX_ARTIFACT_NAME }}
          path: build/bin/LightFX

      - name: Upload uvunwrap Artifact
        uses: actions/upload-artifact@v4
        with: 
          name: ${{ env.UVUNWRAP_ARTIFACT_NAME }}
          path: build/bin/uvunwrap

