name: Pull Request Test

on: [pull_request]

jobs:
  test:
    name: Test on Windows
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      
      - name: Download Premake
        uses: abel0b/setup-premake@v2.4
        with:
          version: "5.0.0-beta2"

      - name: Install zip
        run: |
          choco install zip -y
    
      - name: Build
        shell: bash
        run: |
          CI/build.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with: 
          name: Windows-artifact
          path: build/bin/Release

  test_on_mac:
    name: Test on macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - name: Install autoconf automake autoconf-archive
        run: |
          brew install autoconf automake autoconf-archive

      - name: Download Premake
        uses: abel0b/setup-premake@v2.4
        with:
          version: "5.0.0-beta2"
  
      - name: Build
        shell: bash
        run: |
          CI/build.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with: 
          name: macOS-artifact
          path: build/bin/Release

